export enum ResponseStatusEnum {
  Success = 0,
  GeneralError = 1,
  Unexpected = 2,
  Validation = 3,
  Conflict = 4,
  NotFound = 5,
  Unauthorized = 6,
  Forbidden = 7,
  InvalidSignature = 8,
  InvalidSessionKey = 9,
  AccountNotVerified = 10,
  InvalidAccount = 11,
  InvalidRequest = 12,
  InvalidPassword = 13,
  EmailError = 14,
  MetersAssignedBefore = 15,
  MeterAlreadyOnCustomer = 16,
  MeterBelongToAnotherAgent = 17,
  InvalidMeter = 18,
}
