// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Ticketing.Infrastructure.Database;

#nullable disable

namespace Modules.Ticketing.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260905113601_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ticketing")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_type");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_attachment");

                    b.ToTable("attachment", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "ticketing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Name = "Recharge Operations",
                            Sort = 1
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Name = "Meter & Customer configuration",
                            Sort = 2
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = true,
                            Name = "Meter Operations",
                            Sort = 3
                        },
                        new
                        {
                            Id = 4,
                            IsVisible = true,
                            Name = "Payment & Settlement Operations",
                            Sort = 4
                        },
                        new
                        {
                            Id = 5,
                            IsVisible = true,
                            Name = "System Configuration Errors",
                            Sort = 5
                        },
                        new
                        {
                            Id = 6,
                            IsVisible = true,
                            Name = "Reports & Data Issues",
                            Sort = 6
                        },
                        new
                        {
                            Id = 7,
                            IsVisible = true,
                            Name = "System Performance & Unexpected Errors",
                            Sort = 7
                        });
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ref_id");

                    b.HasKey("Id")
                        .HasName("pk_operators");

                    b.HasIndex("RefId")
                        .IsUnique()
                        .HasDatabaseName("ix_operators_ref_id");

                    b.ToTable("operators", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.ToTable("service", "ticketing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Name = "Gas",
                            Sort = 1
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Name = "Water",
                            Sort = 2
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = true,
                            Name = "Electric",
                            Sort = 3
                        });
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Severity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_severities");

                    b.ToTable("severities", "ticketing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Name = "Low",
                            Sort = 1
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Name = "Medium",
                            Sort = 2
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = true,
                            Name = "High",
                            Sort = 3
                        },
                        new
                        {
                            Id = 4,
                            IsVisible = true,
                            Name = "Critical",
                            Sort = 4
                        });
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_id");

                    b.Property<string>("OtherTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("other_title");

                    b.Property<int?>("SeverityId")
                        .HasColumnType("int")
                        .HasColumnName("severity_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tickets_category_id");

                    b.HasIndex("SeverityId")
                        .HasDatabaseName("ix_tickets_severity_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_tickets_title_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_tickets_type_id");

                    b.ToTable("tickets", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Commenter")
                        .HasColumnType("int")
                        .HasColumnName("commenter");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_comments_ticket_id");

                    b.ToTable("ticket_comments", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("operator_name");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_histories");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_histories_ticket_id");

                    b.ToTable("ticket_histories", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperatorId")
                        .HasColumnType("int")
                        .HasColumnName("operator_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("role");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_operators");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_ticket_operators_operator_id");

                    b.HasIndex("TicketId", "OperatorId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_operators_ticket_id_operator_id");

                    b.ToTable("ticket_operators", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DefaultSeverityId")
                        .HasColumnType("int")
                        .HasColumnName("default_severity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_titles");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_ticket_titles_category_id");

                    b.ToTable("ticket_titles", "ticketing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 4,
                            Name = "Failed Recharge"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 4,
                            Name = "Wrong Balance After Recharge"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Wrong Payment Type"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Add/Edit (Meter or Customer data )"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 2,
                            Name = "System Card issue"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Customer Card Issue"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Link Meter to Customer Failed"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 2,
                            Name = "Read retrival card issue"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Replace Card Issue"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 2,
                            Name = "Replace Meter Issue"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Adjustment Issue"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Payment Order Issue"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Debit Settlement Issue"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 3,
                            Name = "Pay Adjustment Issue"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 2,
                            Name = "Add/Edit(Users, Privileges, Cashier Holiday, Friendly Time, General Settings,Fees, Tariff, Customer Complaints, Activity, Adjustment Type, Banks, Organization, Replace Meter Reasons, Services)"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 1,
                            Name = "Depends on Report Type"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultSeverityId = 4,
                            Name = "System Crash / Slow / Unexpected Error"
                        });
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_ticket_types");

                    b.ToTable("ticket_types", "ticketing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Name = "Complaint",
                            Sort = 1
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Name = "Inquiry",
                            Sort = 2
                        });
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketsAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by_name");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets_attachments");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_tickets_attachments_ticket_id");

                    b.ToTable("tickets_attachments", "ticketing");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_categories_category_id");

                    b.HasOne("Modules.Ticketing.Domain.Entities.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_severities_severity_id");

                    b.HasOne("Modules.Ticketing.Domain.Entities.TicketTitle", "TicketTitle")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticket_titles_title_id");

                    b.HasOne("Modules.Ticketing.Domain.Entities.TicketType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_types_type_id");

                    b.Navigation("Category");

                    b.Navigation("Severity");

                    b.Navigation("TicketTitle");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketHistories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_histories_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketOperator", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Operator", "Operator")
                        .WithMany("TicketOperators")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_operators_operators_operator_id");

                    b.HasOne("Modules.Ticketing.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketOperators")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_operators_tickets_operator_id");

                    b.Navigation("Operator");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketTitle", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Category", "Category")
                        .WithMany("TicketTitles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_titles_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.TicketsAttachment", b =>
                {
                    b.HasOne("Modules.Ticketing.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Category", b =>
                {
                    b.Navigation("TicketTitles");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Operator", b =>
                {
                    b.Navigation("TicketOperators");
                });

            modelBuilder.Entity("Modules.Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketComments");

                    b.Navigation("TicketHistories");

                    b.Navigation("TicketOperators");
                });
#pragma warning restore 612, 618
        }
    }
}
