// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Users.Infrastructure.Database;

#nullable disable

namespace Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260807174150_InintOrg")]
    partial class InintOrg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("org")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agents", "org");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.AgentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgentRoles", "org");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FirstLine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SecondLine"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TeamLead"
                        });
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Customers", "org");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations", "org");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.OrganizationAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("AgentRoleId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("AgentRoleId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationAgents", "org");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Customer", b =>
                {
                    b.HasOne("Modules.Users.Domain.OrganizationAggregate.Organization", "Organization")
                        .WithMany("OrganizationCustomers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.OrganizationAgent", b =>
                {
                    b.HasOne("Modules.Users.Domain.OrganizationAggregate.Agent", "Agent")
                        .WithMany("AgentOrganizations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Users.Domain.OrganizationAggregate.AgentRole", "AgentRole")
                        .WithMany()
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modules.Users.Domain.OrganizationAggregate.Organization", "Organization")
                        .WithMany("OrganizationAgents")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("AgentRole");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Agent", b =>
                {
                    b.Navigation("AgentOrganizations");
                });

            modelBuilder.Entity("Modules.Users.Domain.OrganizationAggregate.Organization", b =>
                {
                    b.Navigation("OrganizationAgents");

                    b.Navigation("OrganizationCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
