export enum HttpVerb {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
}

export enum EndPoint {
  GET_TICKETS = 'Ticket/list',
  GET_TICKETS_FOR_ADMIN = 'Ticket/admin/{adminId}',
  GET_TICKET_DETAILS = 'Ticket/GetTicketDetails/{ticketId}',
  GET_TICKET_HISTORY = 'Ticket/{ticketId}/history',
  // Email notification endpoints
  SEND_COMMENT_NOTIFICATION = 'Ticket/sendCommentNotification',
  SEND_STATUS_CHANGE_NOTIFICATION = 'Ticket/sendStatusChangeNotification',
  SEND_TICKET_UPDATE_NOTIFICATION = 'Ticket/sendTicketUpdateNotification',
  GET_TICKET_COMMENTS = 'Ticket/GetTicketComments',
  DISTRICTS_LIST = 'Districts/ActiveDistrics/list',
  INSTALLED_METERS = 'meters/installed',
  GET_CONTRACTORS = 'contractors/all',
  GET_Contractors_BY_DISTRICT_ID = 'Districts/Contractors',
  ASSIGN_METER_TO_CONTRACTOR = 'Districts/All-Contractors',
  RETIRED_METERS = 'Meters/retired',
  DISTRICTS = 'Districts/all',
  METERS_STATISTICS = 'meters/statistics',
  RETIRED_METER_STATISTICS = 'Dashboard/retired/status/district',
  AGENTS_OPERATIONS_STATISTICS = 'agents/operations/statistics',
  CHANGE_PASSWORD = 'account/ChangePassword',
  GET_AGENTS_BY_CONTRACTOR_ID = 'contractors/{contractorId}/agents',
  MOCK_AGENTS = './mock/agents.mock.json',
  UPDATE_AGENT = 'agents/edit',
  UPDATE_AGENT_STATUS = 'agents/{agentId}/status',
  GET_AGENT_BY_ID = 'agents',
  UPDATE_CONTRACTOR = 'contractors/edit',
  GET_CONTRACTOR_BY_ID = 'contractors',
  ADD_CONTRACTOR = 'contractors/add',
  INSTALLED_METERS_DETAILS = 'meters/{meterId}/details',
  ASSIGN_METER_TO_AGENT = 'meters/assign-to-contractor',
  EXPORT_CONTRACTORS = 'contractors/export',
  EXPORT_AGENTS = 'agents/export',
  GET_AUDITS = 'audits/get_audits',
  Get_USERS = 'User/search-users',
  EXPORT_INSTALLED_METERS = 'meters/installed/export',
  CONTRACTORS = 'contractors/list',
  METER_TYPES = 'Lockups/meter-types',
  METER_MAKES = 'Lockups/meter-make',
  EXPORT_RETIRED_METERS = 'meters/retired/export',
  AddTicket = 'Ticket/AddTicket',
  UPLOAD_ATTACHMENT = 'Attachments/{attachmentTypeId}/{referenceId}',
  SET_ATTACHMENT_REFERENCE = 'Attachments/{attachmentId}/set-reference/{referenceId}',
  DOWNLOAD_TICKET_ATTACHMENT = 'Attachments/download/{ticketId}',
  DELETE_ATTACHMENT = 'Attachments/{attachmentId}',
  AGENTS_LIST = 'agents',
  ADD_AGENT = 'agents',
  ORGANIZATIONS_LIST = 'organizations',
  ADD_ORGANIZATION = 'organizations',
  CUSTOMERS_LIST = 'customer',
  ORGANIZATION_CUSTOMERS = 'Organizations/customers',
}
